# .github/release.yml

changelog:
  categories:
    - title: 🎀 Enhancements!
      labels:
        - enhancements
        - release
      exclude:
        labels:
          - fix
          - feature
    - title: 🛠 Fix!
      labels:
        - fix
        - release
      exclude:
        labels:
          - enhacements
          - feature
    - title: 🎉 Feature!
      labels:
          - feature
          - release
      exclude:
        labels:
          - fix
          - enhancements
