# .github/release.yml

changelog:
  categories:
    - title: Feature
      labels:
        - enhacements
        - release
      exclude:
        labels:
          - fix
    - title: Fix
      labels:
        - release
        - fix
