# .github/release.yml

changelog:
  categories:
    - title: Enhacements
      labels:
        - release
        - enhacements
      exclude:
        labels:
          - fix
    - title: Fix
      labels:
      	- release
        - fix
        exclude:
        labels:
          - feature
        
