# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - belon97
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Updating-featues
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Updating-featues
        - enhancement
    - title: Other Changes
      labels:
        - "*"
